### ISSUE TITLE
Error when running latest versions of REACH on MITRE assembly documents (running remotely on CMU machines)

### ISSUE THREAD

**Issue by ghost** [clulab/reach#112]
Running the latest version of REACH on the documents pointed at for MITRE causes an error. 

The document pmcids are: PMC4345513, PMC3178447, PMC3690480, PMC534114

The error trace is:

initializing NxmlReader ...
Skipping sentence of length 188
Skipping sentence of length 125
Skipping sentence of length 111
[error](run-main-0) java.lang.NoClassDefFoundError: Could not initialize class edu.arizona.sista.reach.grounding.ReachKBKeyTransforms$
java.lang.NoClassDefFoundError: Could not initialize class edu.arizona.sista.reach.grounding.ReachKBKeyTransforms$
    at edu.arizona.sista.reach.grounding.IMKBProteinMentionLookup.resolve(IMKBProteinMentionLookup.scala:22)
    at edu.arizona.sista.reach.grounding.ReachEntityLookup$$anonfun$augmentMention$1.apply(ReachEntityLookup.scala:57)
    at edu.arizona.sista.reach.grounding.ReachEntityLookup$$anonfun$augmentMention$1.apply(ReachEntityLookup.scala:56)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at edu.arizona.sista.reach.grounding.ReachEntityLookup.augmentMention(ReachEntityLookup.scala:56)
    at edu.arizona.sista.reach.grounding.ReachEntityLookup.edu$arizona$sista$reach$grounding$ReachEntityLookup$$resolveMention(ReachEntityLookup.scala:46)
    at edu.arizona.sista.reach.grounding.ReachEntityLookup$$anonfun$apply$1.apply(ReachEntityLookup.scala:24)
    at edu.arizona.sista.reach.grounding.ReachEntityLookup$$anonfun$apply$1.apply(ReachEntityLookup.scala:23)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.Iterator$class.foreach(Iterator.scala:750)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at edu.arizona.sista.reach.grounding.ReachEntityLookup.apply(ReachEntityLookup.scala:23)
    at edu.arizona.sista.reach.ReachSystem.extractEntitiesFrom(ReachSystem.scala:114)
    at edu.arizona.sista.reach.ReachSystem$$anonfun$2.apply(ReachSystem.scala:65)
    at edu.arizona.sista.reach.ReachSystem$$anonfun$2.apply(ReachSystem.scala:65)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at edu.arizona.sista.reach.ReachSystem.extractFrom(ReachSystem.scala:65)
    at edu.arizona.sista.reach.ReachCLI$$anonfun$processPapers$2.apply(ReachCLI.scala:114)
    at edu.arizona.sista.reach.ReachCLI$$anonfun$processPapers$2.apply(ReachCLI.scala:50)
    at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
    at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
    at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
    at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
    at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
    at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
    at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
    at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error](compile:runMain) Nonzero exit code: 1
[error] Total time: 182 s, completed Mar 10, 2016 1:03:53 PM

```
Reverting back to an old version of REACH fixes the problem. 

`$ git checkout f8b1f80f95b805699facc90bdcc870910be5a7c5`

reverted to this version (which ran and completed fine):

commit f8b1f80f95b805699facc90bdcc870910be5a7c5
Merge: 147dc24 f88173f
Author: Gus Hahn-Powell <gushahnpowell@gmail.com>
Date:   Sun Jan 31 20:51:49 2016 -0700




```

**Comment by myedibleenso** [comment]
I'm aware of a different problem that affects one of the papers you've listed, but this particular error sounds like you might want to try a fresh clone of the repo.  Does running `sbt clean` resolve this?

**Comment by hickst** [comment]
Off-hand, this sounds like a class loading problem. We did just release some new library versions and you may have some old compiled code lying around in caches.

If you have already tried a complete recompile 'sbt clean compile' and that did not help, then try removing the following directories before recompiling.
1) $HOME/.ivy2/local directory
2) $HOME/.ivy/cache/org.clulab
3) $HOME/.m2/repository/org/clulab

The first time after removal the compile will be very slow, as it re-downloads all the JARs but this thorough cleaning has almost always solved our problems like this.

**Comment by GullyAPCBurns** [comment]
I'll try it.

G.

**Comment by myedibleenso** [comment]
Any luck?

**Comment by GullyAPCBurns** [comment]
Yep. That fixed it.

Thanks!

Gully
