### ISSUE TITLE
matching empty string

### ISSUE THREAD

**Issue by marcovzla** [clulab/reach#22]
If a token pattern matches an empty string, it breaks with the following error:

```
  java.lang.IllegalArgumentException: requirement failed: invalid range
[info]   at scala.Predef$.require(Predef.scala:219)
[info]   at edu.arizona.sista.struct.Interval.<init>(Interval.scala:11)
[info]   at edu.arizona.sista.odin.impl.TokenPattern$$anonfun$1.apply(TokenPattern.scala:32)
[info]   at edu.arizona.sista.odin.impl.TokenPattern$$anonfun$1.apply(TokenPattern.scala:26)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[info]   at scala.collection.immutable.List.map(List.scala:285)
[info]   at edu.arizona.sista.odin.impl.TokenPattern.findPrefixOf(TokenPattern.scala:26)
[info]   ...
```

maybe we should at least give an easier to interpret error message

**Comment by myedibleenso** [comment]
@marcovzla, did we end up covering this one when we added more descriptive Odin exceptions?

**Comment by myedibleenso** [comment]
@marcovzla, can you give a minimal "working" example for this (rule + text)?

**Comment by marcovzla** [comment]
I will try to replicate this by tomorrow

**Comment by myedibleenso** [comment]
Any luck replicating this?

**Comment by myedibleenso** [comment]
Closing this as it is an `Odin` issue.  

We can reopen in [`processors`](https://github.com/clulab/processors/issues) if needed.
