### ISSUE TITLE
nonUTF-8 default JVM encoding crashes reachnlpprocessors

### ISSUE THREAD

**Issue by antonkulaga** [clulab/reach#222]
When I ran my app that depends on  REACH on the PC with nonUTF-8 default JVM encoding I had issues with automatic models loading (when I start Reach or any other NLPProcessor it crashed). After switching the default JVM encoding to UTF-8 everything went well. I think there are some places in the code where you load model files without specifying the encoding explictely (so the default JVM encoding is used) and when developers use reach as dependency with other default encoding then it fails to load those files correctly.

P.S. Note: as I switched encoding on my server it is not important for me but in the long term it would be nice to fix this bug.

**Comment by antonkulaga** [comment]
Forgot to add a stack trace:
```
Caused by: java.nio.charset.MalformedInputException: Input length = 1
root    at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
root    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
root    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
root    at java.io.InputStreamReader.read(InputStreamReader.java:184)
root    at java.io.BufferedReader.read1(BufferedReader.java:210)
root    at java.io.BufferedReader.read(BufferedReader.java:286)
root    at java.io.Reader.read(Reader.java:140)
root    at scala.io.BufferedSource.mkString(BufferedSource.scala:96)
root    at edu.arizona.sista.odin.impl.RuleReader.edu$arizona$sista$odin$impl$RuleReader$$importRules(RuleReader.scala:171)
root    at edu.arizona.sista.odin.impl.RuleReader$$anonfun$readRules$1.apply(RuleReader.scala:129)
root    at edu.arizona.sista.odin.impl.RuleReader$$anonfun$readRules$1.apply(RuleReader.scala:125)
root    at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
root    at edu.arizona.sista.odin.impl.RuleReader.readRules(RuleReader.scala:125)
root    at edu.arizona.sista.odin.impl.RuleReader.readMasterFile(RuleReader.scala:39)
root    at edu.arizona.sista.odin.impl.RuleReader.read(RuleReader.scala:21)
root    at edu.arizona.sista.odin.ExtractorEngine$.apply(ExtractorEngine.scala:75)
root    at edu.arizona.sista.reach.ReachSystem.<init>(ReachSystem.scala:41)
root    at org.denigma.nlp.extractions.BioExtractor.<init>(BioExtractor.scala:26)
root    at org.denigma.nlp.extractions.NLPActor.<init>(NLPActor.scala:24)
root    ... 18 more
root
```

**Comment by MihaiSurdeanu** [comment]
@terroni, @marcovzla: enforce UTF-8 encoding when Reach starts?

**Comment by cl4yton** [comment]
Marco: this has been fixed in processors: https://github.com/clulab/processors/pull/123
Awaiting development of unit tests to verify before merging and then publishing version of processors with fix.  Marco currently working on unit tests. (Just need example text with weird characters to test response.)
