### ISSUE TITLE
AssemblyCLI has lost ability to read CSV files

### ISSUE THREAD

**Issue by hickst** [clulab/reach#290]
AssemblyCLI was used successfully for the last dry run, which included one test in a CSV input file. Now, however, it seems to fail on the exact same input:
```
[error] (run-main-0) java.lang.IllegalArgumentException: requirement failed: Given /Users/hickst/Documents/nxml2fries/papers/PMC1234335.csv, but readNXMLPaper only handles .nxml files!
java.lang.IllegalArgumentException: requirement failed: Given /Users/hickst/Documents/nxml2fries/papers/PMC1234335.csv, but readNXMLPaper only handles .nxml files!
	at scala.Predef$.require(Predef.scala:224)
	at org.clulab.reach.PaperReader$.readPaper(PaperReader.scala:74)
	at org.clulab.reach.PaperReader$.getMentionsFromPaper(PaperReader.scala:81)
	at org.clulab.reach.AssemblyCLI$$anonfun$processPapers$1.apply(AssemblyCLI.scala:51)
	at org.clulab.reach.AssemblyCLI$$anonfun$processPapers$1.apply(AssemblyCLI.scala:42)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
```

**Comment by myedibleenso** [comment]
This is related to the changes that were made when integrating the new NXMLReader.

**Comment by hickst** [comment]
Yea, I figured as much but we really may need to read CSV files for the evaluation so we should make sure this works again.

**Comment by MihaiSurdeanu** [comment]
Yes, it is possible to get papers in CSV format...
