### ISSUE TITLE
Error running REACH fatjar at the command line

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#412]
Hi,

I built the REACH fatjar to use at the command line on Amazon EC2. I added the following line into build.sbt to define the main class:

```mainClass in assembly := Some("org.clulab.reach.ReachCLI")```

I can successfully build but then when I attempt to run with

```java -jar /pmc/reach/target/scala-2.11/reach-gordo-1.3.3-SNAPSHOT.jar indra.conf```

I get the following error:

```
$ java -jar /pmc/reach/target/scala-2.11/reach-gordo-1.3.3-SNAPSHOT.jar indra.conf 
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'logging'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
	at org.clulab.reach.ReachCLI$.delayedEndpoint$org$clulab$reach$ReachCLI$1(ReachCLI.scala:237)
	at org.clulab.reach.ReachCLI$delayedInit$body.apply(ReachCLI.scala:226)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.clulab.reach.ReachCLI$.main(ReachCLI.scala:226)
	at org.clulab.reach.ReachCLI.main(ReachCLI.scala)
```

Thanks for any help!

**Comment by hickst** [comment]
Hi John,

When you built the FAT JAR had you updated your application.conf file for the target environment?

The default logging section in the application.conf file looks like this (which probably isn't what you want):

```
logging {
  # defines project-wide logging level
  loglevel = INFO
  logfile = ${HOME}/Documents/reach/reach.log
}

```

**Comment by johnbachman** [comment]
Whoops--as you say, just figured out that I need to add the logging section to my configuration file (indra.conf in this case). It's working now :)
