### ISSUE TITLE
Reach error reading rules

### ISSUE THREAD

**Issue by hickst** [clulab/reach#415]
I'm stuck on a mysterious error that's preventing me from deploying a new Reach website. When I run the BioVisualizer web app on Tomcat on Mac, it works fine. When I try the same WAR file on the  same version of Tomcat (with same version of Java) on my Linux system, it fails. I've tried both traditional WAR file and WAR file with one big Reach FAT JAR -- same error. The error appears to be down in the RuleReader implementation:
```
2016-10-23 09:40:49,930 [localhost-startStop-1] INFO  conf.BootStrap  - (BootStrap.init): hostname=esne
2016-10-23 09:47:14,423 [http-bio-8080-exec-5] ERROR errors.GrailsExceptionResolver  - MalformedInputException occurred when processing request: [POST] /odinweb/bio/submit
Input length = 1. Stacktrace follows:
java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.read1(BufferedReader.java:210)
        at java.io.BufferedReader.read(BufferedReader.java:286)
        at java.io.Reader.read(Reader.java:140)
        at scala.io.BufferedSource.mkString(BufferedSource.scala:96)
        at org.clulab.odin.impl.RuleReader.org$clulab$odin$impl$RuleReader$$importRules(RuleReader.scala:187)
        at org.clulab.odin.impl.RuleReader$$anonfun$readRules$1.apply(RuleReader.scala:133)
        at org.clulab.odin.impl.RuleReader$$anonfun$readRules$1.apply(RuleReader.scala:129)
        at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
        at org.clulab.odin.impl.RuleReader.readRules(RuleReader.scala:129)
        at org.clulab.odin.impl.RuleReader.readMasterFile(RuleReader.scala:41)
        at org.clulab.odin.impl.RuleReader.read(RuleReader.scala:20)
        at org.clulab.odin.ExtractorEngine$.apply(ExtractorEngine.scala:75)
        at org.clulab.reach.ReachSystem.<init>(ReachSystem.scala:44)
        at org.clulab.reach.export.apis.Ruler$.<init>(Ruler.scala:19)
        at org.clulab.odinweb.DemoService.processReach(DemoService.groovy:46)
        at org.clulab.odinweb.BioController.submit(BioController.groovy:76)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

The first two lines of the Ruler Object are:
```
  val reachRules = RuleReader.mkRules()
  // pass in reachRules
  val reach = new ReachSystem(Some(reachRules))
```
and I've verified that the `RuleReader.mkRules()` call is returning a `case Class Rules` instance with all 4 fields (entities, modifications, events, context) filled with what looks like good rule sets.

The telling thing here is that the same JAR works on my development system but not on the "pseudo-production" system. Any ideas on how to fix (or even track this down)?

**Comment by myedibleenso** [comment]
We're working on another issue right now.  

If this is urgent, @hickst, can you try debugging this a bit more on your own first (add some logging lines right before those failing calls, etc.)?

Also, what was the last reach version that you successfully used with this component of the website?

**Comment by marcovzla** [comment]
what is the default charset in your linux machine?

**Comment by hickst** [comment]
reach_2.11-1.2.3 but that doesn't tell you much since we don't increment the version numbers often enough -- the version running successfully on Agathon is from March 12th, 2016. Processors version is 5.8.1 from March 8th, 2016.

charset -- now that's a plausible lead to investigate...thanks!

**Comment by hickst** [comment]
@marcovzla Thanks Marco: the locale settings were the problem but it took me an hour to figure out why they were not being properly initialized on that machine only.

**Comment by hickst** [comment]
@marcovzla I really appreciate your help finding the problem but perhaps the reader should catch this error and give a better message. I wasted time trying to figure out why the input was empty when it really wasn't (implied by the message of the thrown exception). It seems like the wrong character set could be a fairly common mistake for some users (with Windows inputs)?

**Comment by marcovzla** [comment]
I agree the reader should either be more robust to encoding or at least produce a more informative error. The grammars included in the jar are utf8 encoded, so no need to query based on the locale. On the other hand, new grammars may have a different encoding. Maybe we should add encoding as a configuration option instead of using the default one?

**Comment by myedibleenso** [comment]
I guess this is related to #222
