### ISSUE TITLE
TestJSONSerializer fails with released Processors 6.0.5

### ISSUE THREAD

**Issue by hickst** [clulab/reach#506]
@myedibleenso I think we discussed this particular issue before but the problem is still around and it means the Reach master tests don't pass with the currently released Processors 6.0.5.

```
[info] JSONSerializer
[info] - should serialize a Seq[BioMention] to json correctly (356 milliseconds)
[info] - should deserialize a Seq[BioMention] from json correctly (6 milliseconds)
[info] - should serialize/deserialize a BioMention to/from json correctly (12 milliseconds)
[info] - should serialize a Seq[CorefMention] to json correctly (9 milliseconds)
[info] - should deserialize a Seq[CorefMention] from json correctly (5 milliseconds)
[info] - should serialize/deserialize a CorefMention to/from json correctly (4 milliseconds)
[info] - should produce identical json for a Seq[CorefMention] before and after serialization/deserialization (29 milliseconds)
[info] json for 'Phosphorylated MEK activates K-RAS.'
[info] - should be identical before and after serialization/deserialzation (5 milliseconds)
[info] - should contain a modification with "modification-type" PTM *** FAILED *** (4 milliseconds)
[info]   org.json4s.package$MappingException: Do not know how to convert JArray(List(JString(PTM))) into class java.lang.String
[info]   at org.json4s.Extraction$.convert(Extraction.scala:702)
[info]   at org.json4s.Extraction$.extract(Extraction.scala:388)
[info]   at org.json4s.Extraction$.extract(Extraction.scala:39)
[info]   at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
[info]   at org.clulab.reach.mentions.serialization.TestJSONSerializer$$anonfun$9.apply$mcV$sp(TestJSONSerializer.scala:97)
[info]   at org.clulab.reach.mentions.serialization.TestJSONSerializer$$anonfun$9.apply(TestJSONSerializer.scala:93)
[info]   at org.clulab.reach.mentions.serialization.TestJSONSerializer$$anonfun$9.apply(TestJSONSerializer.scala:93)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info] - should still contain a PTM after serialization/deserialization *** FAILED *** (6 milliseconds)
[info]   org.json4s.package$MappingException: Do not know how to convert JArray(List(JString(PTM))) into class java.lang.String
[info]   at org.json4s.Extraction$.convert(Extraction.scala:702)
[info]   at org.json4s.Extraction$.extract(Extraction.scala:388)
[info]   at org.json4s.Extraction$.extract(Extraction.scala:39)
[info]   at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
[info]   at org.clulab.reach.mentions.serialization.TestJSONSerializer$$anonfun$10.apply$mcV$sp(TestJSONSerializer.scala:105)
[info]   at org.clulab.reach.mentions.serialization.TestJSONSerializer$$anonfun$10.apply(TestJSONSerializer.scala:100)
[info]   at org.clulab.reach.mentions.serialization.TestJSONSerializer$$anonfun$10.apply(TestJSONSerializer.scala:100)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
```

**Comment by myedibleenso** [comment]
@hickst, the tests have been fixed on the `json-fix` branch.  I've only run the `TestJSONSerializer` suite (all of these tests now pass), so I am still unsure if upgrading to processors v6.0.5 breaks anything else.
