### ISSUE TITLE
New labels causing errors

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#513]
The rule
```
 - name: domains                                                                 
    label: Domain                                                                 
    action: mkBioMention                                                          
    priority: "6"                                                                 
    type: token                                                                   
    pattern: |                                                                    
        [word=/(?i)sh2/ & incoming=nn]
```
with Domain being at the top level of the taxonomy (right next to Site) causes the shell to crash on the sentence `GRB2 has an SH2 domain`:
```
[error] (run-main-0) java.util.NoSuchElementException: None.get
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at org.clulab.coref.Coref$$anonfun$apply$39$$anonfun$apply$41.apply(Coref.scala:438)
        at org.clulab.coref.Coref$$anonfun$apply$39$$anonfun$apply$41.apply(Coref.scala:437)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.clulab.coref.Coref$$anonfun$apply$39.apply(Coref.scala:436)
        at org.clulab.coref.Coref$$anonfun$apply$39.apply(Coref.scala:433)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.clulab.coref.Coref.apply(Coref.scala:433)
        at org.clulab.reach.ReachSystem.resolveCoref(ReachSystem.scala:238)
...
```

**Comment by myedibleenso** [comment]
@danebell, I think this `Mention` isn't being grounded, but `Coref` is expecting it to be.  As an extension, one option may be to bypass the current extractor engines and the rule in run another engine instance that is initialized with their output.  I suspect the `Mention` will still need a (UAZ) grounding to be compatible with the rest of the system.
