### ISSUE TITLE
Issue with compiling single FAT JAR

### ISSUE THREAD

**Issue by JohnGiorgi** [clulab/reach#535]
As per the suggestion in #531, I tried to compile a single FAT JAR using `sbt assembly`. 

The error I get is:
 ```
[error] (root/*:assembly) deduplicate: different file contents found in the following:
[error] /Users/johngiorgi/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/options.xml
[error] /Users/johngiorgi/.ivy2/cache/org.clulab/processors-models_2.11/jars/processors-models_2.11-6.0.7.jar:appdata/options.xml
``` 
The error is shown muliple times. I tried clearing `/Users/johngiorgi/.ivy2/cache` but this did not fix the problem. Any Idea how I might fix this? Thanks so much in advance!

Here is (what I imagine) the useful output when the error occurred:

```
[info] Checking every *.class/*.jar file's SHA-1.
[info] Merging files...
[warn] Merging 'META-INF/ECLIPSEF.RSA' with strategy 'discard'
[warn] Merging 'META-INF/ECLIPSEF.SF' with strategy 'discard'
[warn] Merging 'META-INF/MANIFEST.MF' with strategy 'discard'
[warn] Merging 'META-INF/maven/args4j/args4j/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/args4j/args4j/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/cc.mallet/mallet/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/cc.mallet/mallet/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/ch.qos.logback/logback-classic/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/ch.qos.logback/logback-classic/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/ch.qos.logback/logback-core/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/ch.qos.logback/logback-core/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.carrotsearch/hppc/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.carrotsearch/hppc/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.clearnlp/clearnlp/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.clearnlp/clearnlp/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.fasterxml.jackson.core/jackson-annotations/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.fasterxml.jackson.core/jackson-annotations/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.fasterxml.jackson.core/jackson-core/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.fasterxml.jackson.core/jackson-core/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.fasterxml.jackson.core/jackson-databind/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.fasterxml.jackson.core/jackson-databind/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.google.guava/guava/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.google.guava/guava/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.googlecode.efficient-java-matrix-library/ejml/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.googlecode.efficient-java-matrix-library/ejml/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.ning/async-http-client/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.ning/async-http-client/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.thoughtworks.paranamer/paranamer/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/com.thoughtworks.paranamer/paranamer/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-codec/commons-codec/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-codec/commons-codec/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-io/commons-io/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-io/commons-io/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-lang/commons-lang/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-lang/commons-lang/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-logging/commons-logging/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/commons-logging/commons-logging/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/de.bwaldvogel/liblinear/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/de.bwaldvogel/liblinear/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/de.jollyday/jollyday/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/de.jollyday/jollyday/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/edu.washington.cs.knowitall/morpha-stemmer/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/edu.washington.cs.knowitall/morpha-stemmer/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/io.netty/netty/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/io.netty/netty/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/javax.json/javax.json-api/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/javax.json/javax.json-api/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/javax.xml.bind/jaxb-api/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/javax.xml.bind/jaxb-api/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/jline/jline/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/jline/jline/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/joda-time/joda-time/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/joda-time/joda-time/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/log4j/log4j/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/log4j/log4j/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/net.sf.jwordnet/jwnl/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/net.sf.jwordnet/jwnl/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/net.sourceforge.jregex/jregex/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/net.sourceforge.jregex/jregex/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.antlr/antlr4-runtime/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.antlr/antlr4-runtime/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.apache.commons/commons-lang3/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.apache.commons/commons-lang3/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.biopax.paxtools/paxtools-core/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.biopax.paxtools/paxtools-core/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.choco-solver/choco-graph/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.choco-solver/choco-graph/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.choco-solver/choco-solver/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.choco-solver/choco-solver/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-continuation/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-continuation/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-http/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-http/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-io/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-io/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-security/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-security/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-server/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-server/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-servlet/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-servlet/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-util/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-util/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-webapp/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-webapp/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-xml/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.eclipse.jetty/jetty-xml/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.hamcrest/hamcrest-core/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.hamcrest/hamcrest-core/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.javabits.jgrapht/jgrapht-core/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.javabits.jgrapht/jgrapht-core/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.slf4j/slf4j-api/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.slf4j/slf4j-api/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.yaml/snakeyaml/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/org.yaml/snakeyaml/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/maven/tw.edu.ntu.csie/libsvm/pom.properties' with strategy 'discard'
[warn] Merging 'META-INF/maven/tw.edu.ntu.csie/libsvm/pom.xml' with strategy 'discard'
[warn] Merging 'META-INF/services/org.apache.lucene.codecs.DocValuesFormat' with strategy 'filterDistinctLines'
[warn] Merging 'META-INF/services/org.apache.lucene.codecs.PostingsFormat' with strategy 'filterDistinctLines'
[warn] Merging 'reference.conf' with strategy 'concat'
[error] 2 errors were encountered during merge
java.lang.RuntimeException: deduplicate: different file contents found in the following:
/Users/johngiorgi/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/options.xml
/Users/johngiorgi/.ivy2/cache/org.clulab/processors-models_2.11/jars/processors-models_2.11-6.0.7.jar:appdata/options.xml
deduplicate: different file contents found in the following:
/Users/johngiorgi/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/release.properties
/Users/johngiorgi/.ivy2/cache/org.clulab/processors-models_2.11/jars/processors-models_2.11-6.0.7.jar:appdata/release.properties
	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:140)
	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
	at sbtassembly.Assembly$.apply(Assembly.scala:83)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:240)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:237)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (root/*:assembly) deduplicate: different file contents found in the following:
[error] /Users/johngiorgi/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/options.xml
[error] /Users/johngiorgi/.ivy2/cache/org.clulab/processors-models_2.11/jars/processors-models_2.11-6.0.7.jar:appdata/options.xml
[error] deduplicate: different file contents found in the following:
[error] /Users/johngiorgi/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/release.properties
[error] /Users/johngiorgi/.ivy2/cache/org.clulab/processors-models_2.11/jars/processors-models_2.11-6.0.7.jar:appdata/release.properties
[error] Total time: 85 s, completed 2-Aug-2017 10:54:47 AM
```

**Comment by hickst** [comment]
Thanks for catching this. We had forgotten to update a resource area when we updated one of the libraries that Processors depends on. It passed all our code tests because the clash **only** happens when one tries to create the FAT JAR.

Unfortunately, until we release the next Processors and Reach versions, you will have to compile (and use) your own local, SNAPSHOT version of Processors. To do this:
1. `git clone git@github.com:clulab/processors.git`
2. `cd processors`
3. `sbt compile publishLocal`

To use that local version of Processors 6.0.8-SNAPSHOT in your local copy of Reach:

0. **[only if you don't already have a local working copy of Reach]:** 
`git clone git@github.com:clulab/reach.git; cd reach`
1. edit main/build.sbt, and change:
`val procVer = "6.0.7"`
to
`val procVer = "6.0.8-SNAPSHOT"`
2. recompile your local Reach FAT JAR: `sbt assembly`

If you encounter any problems or have any questions, please let us know.
