### ISSUE TITLE
REACH build error due to failed download of corenlp

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#546]
Hi there,

I get the following error when I try to build the latest reach (Fatjar). Any help appreciated. Thanks!

```[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.clulab#processors-corenlp_2.11;6.1.2!processors-corenlp_2.11.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: org.clulab#processors-corenlp_2.11;6.1.2!processors-corenlp_2.11.jar
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (main/*:update) sbt.ResolveException: download failed: org.clulab#processors-corenlp_2.11;6.1.2!processors-corenlp_2.11.jar
[error] Total time: 34 s, completed Sep 14, 2017 3:30:54 PM
```

**Comment by hickst** [comment]
I see this JAR (and the other Reach) JARs in Maven Central. I note that it is a download failure, as if you are having network problems reaching Maven Central. Do the other Reach JARs download?

I just tried a new "clean" installation on another computer and it downloaded the Reach JARs without problem:
```
[info] downloading https://repo1.maven.org/maven2/org/clulab/bioresources/1.1.24/bioresources-1.1.24.jar ...
[info] 	[SUCCESSFUL ] org.clulab#bioresources;1.1.24!bioresources.jar (6428ms)
[info] downloading https://repo1.maven.org/maven2/org/clulab/processors-main_2.11/6.1.2/processors-main_2.11-6.1.2.jar ...
[info] 	[SUCCESSFUL ] org.clulab#processors-main_2.11;6.1.2!processors-main_2.11.jar (349ms)
[info] downloading https://repo1.maven.org/maven2/org/clulab/processors-corenlp_2.11/6.1.2/processors-corenlp_2.11-6.1.2.jar ...
[info] 	[SUCCESSFUL ] org.clulab#processors-corenlp_2.11;6.1.2!processors-corenlp_2.11.jar (155ms)
[info] downloading https://repo1.maven.org/maven2/org/clulab/processors-models_2.11/6.1.2/processors-models_2.11-6.1.2.jar ...
[info] 	[SUCCESSFUL ] org.clulab#processors-models_2.11;6.1.2!processors-models_2.11.jar (46230ms)
[info] downloading https://repo1.maven.org/maven2/org/clulab/processors-odin_2.11/6.1.2/processors-odin_2.11-6.1.2.jar ...
[info] 	[SUCCESSFUL ] org.clulab#processors-odin_2.11;6.1.2!processors-odin_2.11.jar (233ms)
```

This really looks to me like a problem contacting Maven Central but, in general, there are several other things you can try if you encounter compilation problems:
1. `rm -rf ~/.ivy2/local`
2. `rm -rf ~/.ivy2/cache/org.clulab`
3. Clone Reach entirely anew from GitHub: `git clone git@github.com:clulab/reach.git`

**Comment by johnbachman** [comment]
Hmm. I got this error building johnbachman/indra_deps_docker on Amazon Codebuild (so presumably not a internet issue) and then reproduced it on my local machine. Because the docker build in indra_deps_docker starts from a clean ubuntu machine, it seems unlikely that it's an issue with the ivy cache...but I will try that on my local machine to see if that fixes it.

**Comment by hickst** [comment]
I'm not familiar with Amazon Codebuild but is it possible that they use their own repository servers (and not Maven Central where our artifacts are located)?

Looking at the error message you posted above it  looks to me like `sbt` is sayIng "Hey, I can't find and/or download the processors-corenlp_2.11.jar file" and, since that JAR file *is* available from Maven Central, it doesn't seem like a problem with the Reach system.

**Comment by johnbachman** [comment]
OK, interesting. On my local machine when I blew away the .ivy2 cache I was able to build successfully. Not sure why this would be failing on AWS given that it starts the build from a clean slate. Hmm.

**Comment by johnbachman** [comment]
Here is the procedure we have for installing Java, SBT, and REACH on our docker image (see https://github.com/johnbachman/indra_deps_docker/blob/master/Dockerfile):

```
echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | \
                                               debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    update-java-alternatives -s java-8-oracle && \
    apt-get install -y oracle-java8-set-default && \
    # Install SBT
    # http://stackoverflow.com/questions/13711395/install-sbt-on-ubuntu
    # (Note that the instructions at
    # http://www.scala-sbt.org/release/docs/Installing-sbt-on-Linux.html
    # did not work)
    wget http://apt.typesafe.com/repo-deb-build-0002.deb && \
    dpkg -i repo-deb-build-0002.deb && \
    apt-get update && \
    apt-get install -y sbt && \
    # Fix error with missing sbt launcher
    # http://stackoverflow.com/questions/36234193/cannot-build-sbt-project-due-to-launcher-version
    wget http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.13/sbt-launch.jar -P /root/.sbt/.lib/0.13.13 && \
    # Get and build the latest REACH
    git clone https://github.com/clulab/reach.git && \
    cd reach && \
    git checkout 735b930f5ed2ddd1b7f9ce && \
    echo 'mainClass in assembly := Some("org.clulab.reach.RunReachCLI")' >> build.sbt && \
    sbt assembly && \
```

**Comment by johnbachman** [comment]
In the Amazon build logs, I noticed the following earlier line when it was resolving locations of everything:

```
[0m[[31merror[0m] [0mSERVER ERROR: Slow Down url=https://repo1.maven.org/maven2/org/clulab/processors-corenlp_2.11/6.1.2/processors-corenlp_2.11-6.1.2.jar[0m
```

**Comment by johnbachman** [comment]
Looks like it worked! Must have been some kind of temporary issue.

**Comment by hickst** [comment]
Great! Always glad to hear when a problem goes away.
     cheers,
        -t
