### ISSUE TITLE
Using Reach from a FAT JAR

### ISSUE THREAD

**Issue by JohnGiorgi** [clulab/reach#564]
I am having an issue using reach from a FAT JAR. Following the instructions on the [wiki](https://github.com/clulab/reach/wiki/Using-Reach-from-a-FAT-JAR), I ran

```
sbt assembly
```

And then
```
java -jar reach-1.4.1-SNAPSHOT-FAT.jar
```

Judging by the output, the issue begins with this line:

```
[WARN] [11/20/2017 19:02:26.001] [New I/O boss #3] [NettyTransport(akka://procClient)] Remote connection to [null] failed with java.net.ConnectException: Connection refused: /127.0.0.1:2552
```

I am not sure how to debug the issue. Any advice? (tried some simple stuff like freshly installing `sbt`).

Full output for reference:

```
Loading ReachSystem ...
[INFO] [11/20/2017 19:02:24.699] [main] [akka.remote.Remoting] Starting remoting
[INFO] [11/20/2017 19:02:24.871] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://procClient@127.0.0.1:50241]
[INFO] [11/20/2017 19:02:24.872] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://procClient@127.0.0.1:50241]
[WARN] [11/20/2017 19:02:26.001] [New I/O boss #3] [NettyTransport(akka://procClient)] Remote connection to [null] failed with java.net.ConnectException: Connection refused: /127.0.0.1:2552
[WARN] [11/20/2017 19:02:26.003] [procClient-akka.remote.default-remote-dispatcher-5] [akka.tcp://procClient@127.0.0.1:50241/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FprocServer%40127.0.0.1%3A2552-0] Association with remote system [akka.tcp://procServer@127.0.0.1:2552] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://procServer@127.0.0.1:2552]] Caused by: [Connection refused: /127.0.0.1:2552]
[INFO] [11/20/2017 19:02:26.009] [procClient-akka.actor.default-dispatcher-4] [akka://procClient/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FprocServer%40127.0.0.1%3A2552-0/endpointWriter] Message [akka.remote.EndpointWriter$AckIdleCheckTimer$] from Actor[akka://procClient/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FprocServer%40127.0.0.1%3A2552-0/endpointWriter#-118035839] to Actor[akka://procClient/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FprocServer%40127.0.0.1%3A2552-0/endpointWriter#-118035839] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
19:02:26.011 [main] ERROR o.c.p.client.ProcessorClient - (ProcessorClient): Unable to find or connect to the Server.
Exception in thread "main" java.lang.RuntimeException: (ProcessorClient): Unable to find or connect to the Server.
	at org.clulab.processors.client.ProcessorClient.getRouterRef(ProcessorClient.scala:100)
	at org.clulab.processors.client.ProcessorClient.<init>(ProcessorClient.scala:80)
	at org.clulab.processors.client.ProcessorClient$.instance(ProcessorClient.scala:37)
	at org.clulab.reach.ProcessorAnnotatorFactory$.makeProcessorAnnotator(ProcessorAnnotatorFactory.scala:35)
	at org.clulab.reach.ProcessorAnnotatorFactory$.apply(ProcessorAnnotatorFactory.scala:27)
	at org.clulab.reach.ReachShell$.delayedEndpoint$org$clulab$reach$ReachShell$1(ReachShell.scala:26)
	at org.clulab.reach.ReachShell$delayedInit$body.apply(ReachShell.scala:15)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.clulab.reach.ReachShell$.main(ReachShell.scala:15)
	at org.clulab.reach.ReachShell.main(ReachShell.scala)
[INFO] [11/20/2017 19:02:26.017] [procClient-akka.remote.default-remote-dispatcher-5] [akka.tcp://procClient@127.0.0.1:50241/system/remoting-terminator] Shutting down remote daemon.
[INFO] [11/20/2017 19:02:26.018] [procClient-akka.remote.default-remote-dispatcher-5] [akka.tcp://procClient@127.0.0.1:50241/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [11/20/2017 19:02:26.044] [procClient-akka.actor.default-dispatcher-2] [akka.remote.Remoting] Remoting shut down
[INFO] [11/20/2017 19:02:26.045] [procClient-akka.remote.default-remote-dispatcher-13] [akka.tcp://procClient@127.0.0.1:50241/system/remoting-terminator] Remoting shut down.
```

**Comment by hickst** [comment]
I'm sorry John: you are the first (but not the last, I suspect) to be caught by the total separation of our Client and Server pieces within Processors. (I have it on my list to update the documentation when I return from my current week of vacation but you were quicker to update than I anticipated).

Basically, to run Reach now, you need to start a Processor Server in a JVM and then start Reach in a separate JVM. 

The clue in the error message above (unfortunately, difficult to see in the noise) is the line which reads:

```19:02:26.011 [main] ERROR o.c.p.client.ProcessorClient - (ProcessorClient): Unable to find or connect to the Server.```

If you run from the command line, you can use our updated script (runReachCLI), which will start the server and then run Reach (which uses the client) for you. (see [runReachCLI](https://github.com/clulab/reach/blob/master/runReachCLI.sh) )

To run Reach via the FAT JAR file, you will have to start an instance of the Processor Server manually before running Reach in the normal way. To start up a Server instance, you must make a different call on the same Reach FAT JAR:

```java -cp ./reach-1.4.1-SNAPSHOT-FAT.jar org.clulab.processors.server.ProcessorServer```

wait a few seconds (5-15)  until you see a message similar to this:

```[INFO] [11/20/2017 18:23:50.088] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://procServer@127.0.0.1:2552]```

and then start Reach from the same FAT JAR, as usual:

```java -jar reach-1.4.1-SNAPSHOT-FAT.jar```

Reach should connect to the Server and run as usual. When Reach finishes processing your input files, it should shutdown both the Server and its internal Client.

If you have any problems, please do not hesitate to get back to us.
    regards,
        -t

**Comment by JohnGiorgi** [comment]
_Please do not worry about answering me until after your vacation!_

Hi Tom, 

Thanks for the quick response. Unless I am doing something seriously wrong (which is entirely possible) I cannot get either of the methods you mention to work.

__(1) Running from the command line__
```
git clone https://github.com/clulab/reach.git
cd reach 
sbt compile
sbt "runMain org.clulab.reach.RunReachCLI"
```

__(2) Running using the FAT JAR__
```
git clone https://github.com/clulab/reach.git
cd reach 
sbt assembly
cd target/scala-2.11
# in first JVM
java -cp ./reach-1.4.1-SNAPSHOT-FAT.jar org.clulab.processors.server.ProcessorServer
# in second JVM
java -jar reach-1.4.1-SNAPSHOT-FAT.jar
```

Both give me errors (which are a little cryptic to me, listed below for reference).

__Output from: (1) Running from the command line__

```
[info] Loading project definition from /Users/johngiorgi/Documents/Masters/Research/PrototypeWorkflow/reach/project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to reach-exe (in build file:/Users/johngiorgi/Documents/Masters/Research/PrototypeWorkflow/reach/)
[info] Running org.clulab.reach.RunReachCLI
11:19:23.445 [run-main-0] INFO  org.clulab.reach.RunReachCLI$ - ReachCLI (w/o assembly) begins ...
11:19:23.539 [run-main-0] INFO  org.clulab.reach.ReachCLI - Initializing Reach ...
[INFO] [11/21/2017 11:19:25.093] [run-main-0] [akka.remote.Remoting] Starting remoting
[INFO] [11/21/2017 11:19:25.502] [run-main-0] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://procClient@127.0.0.1:49534]
[INFO] [11/21/2017 11:19:25.509] [run-main-0] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://procClient@127.0.0.1:49534]
[WARN] [11/21/2017 11:19:25.787] [New I/O boss #3] [NettyTransport(akka://procClient)] Remote connection to [null] failed with java.net.ConnectException: Connection refused: /127.0.0.1:2552
[WARN] [11/21/2017 11:19:25.796] [procClient-akka.remote.default-remote-dispatcher-8] [akka.tcp://procClient@127.0.0.1:49534/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FprocServer%40127.0.0.1%3A2552-0] Association with remote system [akka.tcp://procServer@127.0.0.1:2552] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://procServer@127.0.0.1:2552]] Caused by: [Connection refused: /127.0.0.1:2552]
11:19:25.805 [run-main-0] ERROR o.c.p.client.ProcessorClient - (ProcessorClient): Unable to find or connect to the Server.
[error] (run-main-0) java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at org.clulab.reach.RunReachCLI$.delayedEndpoint$org$clulab$reach$RunReachCLI$1(ReachCLI.scala:322)
	at org.clulab.reach.RunReachCLI$delayedInit$body.apply(ReachCLI.scala:264)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.clulab.reach.RunReachCLI$.main(ReachCLI.scala:264)
	at org.clulab.reach.RunReachCLI.main(ReachCLI.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.RuntimeException: (ProcessorClient): Unable to find or connect to the Server.
	at org.clulab.processors.client.ProcessorClient.getRouterRef(ProcessorClient.scala:100)
	at org.clulab.processors.client.ProcessorClient.<init>(ProcessorClient.scala:80)
	at org.clulab.processors.client.ProcessorClient$.instance(ProcessorClient.scala:37)
	at org.clulab.reach.ProcessorAnnotatorFactory$.makeProcessorAnnotator(ProcessorAnnotatorFactory.scala:35)
	at org.clulab.reach.ProcessorAnnotatorFactory$.apply(ProcessorAnnotatorFactory.scala:27)
	at org.clulab.reach.PaperReader$.<init>(PaperReader.scala:45)
	at org.clulab.reach.PaperReader$.<clinit>(PaperReader.scala)
	at org.clulab.reach.RunReachCLI$.delayedEndpoint$org$clulab$reach$RunReachCLI$1(ReachCLI.scala:322)
	at org.clulab.reach.RunReachCLI$delayedInit$body.apply(ReachCLI.scala:264)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.clulab.reach.RunReachCLI$.main(ReachCLI.scala:264)
	at org.clulab.reach.RunReachCLI.main(ReachCLI.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last root/compile:runMain for the full output.
[INFO] [11/21/2017 11:19:25.819] [procClient-akka.remote.default-remote-dispatcher-7] [akka.tcp://procClient@127.0.0.1:49534/system/remoting-terminator] Shutting down remote daemon.
[INFO] [11/21/2017 11:19:25.823] [procClient-akka.remote.default-remote-dispatcher-7] [akka.tcp://procClient@127.0.0.1:49534/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [11/21/2017 11:19:25.865] [procClient-akka.actor.default-dispatcher-6] [akka.remote.Remoting] Remoting shut down
[INFO] [11/21/2017 11:19:25.867] [procClient-akka.remote.default-remote-dispatcher-7] [akka.tcp://procClient@127.0.0.1:49534/system/remoting-terminator] Remoting shut down.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last root/compile:runMain for the full output.
[error] (root/compile:runMain) Nonzero exit code: 1
[error] Total time: 6 s, completed 21-Nov-2017 11:19:25 AM
```
__Output from: (2) Running using the FAT JAR__

Output from server:
```
[INFO] [11/21/2017 11:38:14.650] [main] [akka.remote.Remoting] Starting remoting
[INFO] [11/21/2017 11:38:14.844] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://procServer@127.0.0.1:2552]
[INFO] [11/21/2017 11:38:14.846] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://procServer@127.0.0.1:2552]
[ERROR] [11/21/2017 11:38:27.813] [procServer-akka.remote.default-remote-dispatcher-13] [akka.tcp://procServer@127.0.0.1:2552/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FprocClient%40127.0.0.1%3A50641-0/endpointWriter] AssociationError [akka.tcp://procServer@127.0.0.1:2552] <- [akka.tcp://procClient@127.0.0.1:50641]: Error [Shut down address: akka.tcp://procClient@127.0.0.1:50641] [
akka.remote.ShutDownAssociation: Shut down address: akka.tcp://procClient@127.0.0.1:50641
Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system terminated the association because it is shutting down.
]
[INFO] [11/21/2017 11:38:27.822] [procServer-akka.remote.default-remote-dispatcher-13] [akka.tcp://procServer@127.0.0.1:2552/system/remoting-terminator] Shutting down remote daemon.
[INFO] [11/21/2017 11:38:27.824] [procServer-akka.remote.default-remote-dispatcher-13] [akka.tcp://procServer@127.0.0.1:2552/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [11/21/2017 11:38:27.859] [procServer-akka.actor.default-dispatcher-4] [akka.remote.Remoting] Remoting shut down
[INFO] [11/21/2017 11:38:27.866] [procServer-akka.remote.default-remote-dispatcher-13] [akka.tcp://procServer@127.0.0.1:2552/system/remoting-terminator] Remoting shut down.
```

Output from client:

```
11:38:25.964 [main] INFO  org.clulab.reach.RunReachCLI$ - ReachCLI (w/o assembly) begins ...
11:38:26.008 [main] INFO  org.clulab.reach.ReachCLI - Initializing Reach ...
[INFO] [11/21/2017 11:38:27.145] [main] [akka.remote.Remoting] Starting remoting
[INFO] [11/21/2017 11:38:27.376] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://procClient@127.0.0.1:50641]
[INFO] [11/21/2017 11:38:27.379] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://procClient@127.0.0.1:50641]
[INFO] [11/21/2017 11:38:27.757] [procClient-akka.remote.default-remote-dispatcher-6] [akka.tcp://procClient@127.0.0.1:50641/system/remoting-terminator] Shutting down remote daemon.
[INFO] [11/21/2017 11:38:27.764] [procClient-akka.remote.default-remote-dispatcher-6] [akka.tcp://procClient@127.0.0.1:50641/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [11/21/2017 11:38:27.862] [procClient-akka.actor.default-dispatcher-4] [akka://procClient/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FprocServer%40127.0.0.1%3A2552-0/endpointWriter] Message [akka.remote.EndpointWriter$AckIdleCheckTimer$] from Actor[akka://procClient/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FprocServer%40127.0.0.1%3A2552-0/endpointWriter#297945744] to Actor[akka://procClient/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FprocServer%40127.0.0.1%3A2552-0/endpointWriter#297945744] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [11/21/2017 11:38:27.920] [procClient-akka.actor.default-dispatcher-3] [akka.remote.Remoting] Remoting shut down
[INFO] [11/21/2017 11:38:27.922] [procClient-akka.remote.default-remote-dispatcher-7] [akka.tcp://procClient@127.0.0.1:50641/system/remoting-terminator] Remoting shut down.
```

**Comment by hickst** [comment]
__(1) To run from the command line you should use the shell script `runReachCLI.sh`:__

```
git clone https://github.com/clulab/reach.git
cd reach 
sbt compile
runReachCLI.sh
```
If you look at the contents of `runReachCLI.sh` you will see that it starts the Server for you, then starts Reach for you (which starts the Client).

__2. Running from FAT JARs__

The commands you show look good, as far as they go. And the log messages show that both Server and Client successfully started up and shut down. But, Reach didn't seem to process any files. Your commands don't show that you configured Reach's `application.conf` file to point to where your input files are stored. This is necessary to do before you compile, unless your files are in the default location (`${HOME}/Documents/reach`). 

I have just updated the Reach Wiki page on running from the FAT JAR:
https://github.com/clulab/reach/wiki/Using-Reach-from-a-FAT-JAR

and there is additional information on configuring Reach in **Step 2** of this Wiki page:
https://github.com/clulab/reach/wiki/Running-REACH  and

Hopefully, these updated pages can get you going again.

**Comment by JohnGiorgi** [comment]
I was careful to configure the `application.conf` to point to my input directory (`papersDir`), but just in case I repeated all steps above after ensuring `application.conf` was set.

Reach seems to think my `papersDir` is empty? Could the issue be that my input files are raw text? [This](https://github.com/clulab/reach/wiki/Supported-Input-Formats#txt-files) link seems to suggest that is okay. 

However, I used the python script [here](https://gist.github.com/myedibleenso/f233359445461a71ad37017393fe921f) to download papers in the `.nxml` format and reach was able to parse the paper. 

Any advice? Does reach not support raw text as input?

**Comment by hickst** [comment]
I didn't realize you were using text files and, when I tried one, it also failed to process. Thanks for finding this issue: we thought we had fixed this a few weeks ago. This should be fixed now. Please pull the latest version of Reach and try again.

**Comment by JohnGiorgi** [comment]
Okay great - that worked! Thanks for all of your help. 

I do have one more lingering question but I think its best if I open a new issue.
