### ISSUE TITLE
Problem with accessing models within Play application

### ISSUE THREAD

**Issue by andrewresearch** [clulab/reach#578]
I'm not sure if this is a bug, or a config error on my part (I suspect the latter).

CluProcessor POS tagging is working fine from the REPL in my play app, but within the running app itself, I'm getting the following NPE whenever I call `processor.annotate(doc)`:

```
Caused by: java.lang.NullPointerException: null
	at java.base/java.io.Reader.<init>(Reader.java:78)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.clulab.sequences.BiMEMMSequenceTagger.load(BiMEMMSequenceTagger.scala:247)
	at org.clulab.sequences.SequenceTagger.loadFromResource(SequenceTagger.scala:35)
	at org.clulab.sequences.SequenceTagger.loadFromResource$(SequenceTagger.scala:33)
	at org.clulab.sequences.BiMEMMSequenceTagger.loadFromResource(BiMEMMSequenceTagger.scala:20)
	at org.clulab.processors.clu.sequences.PartOfSpeechTagger$.loadFromResource(PartOfSpeechTagger.scala:57)
	at org.clulab.processors.clu.CluProcessor.posTagger$lzycompute(CluProcessor.scala:60)
	at org.clulab.processors.clu.CluProcessor.posTagger(CluProcessor.scala:59)
	at org.clulab.processors.clu.CluProcessor.$anonfun$tagPartsOfSpeech$1(CluProcessor.scala:237)
```

I'm assuming that for some reason the processor can't find the necessary models, however I'm not sure why the models aren't being loaded to the class path. I have other NLP software with models running fine within the same app.

**Comment by andrewresearch** [comment]
Found that I had a `Test` at the end of the SBT dependencies for the model - for some unknown reason!
