### ISSUE TITLE
Conflict errors during fat jar assembly

### ISSUE THREAD

**Issue by bgyori** [clulab/reach#627]
With the latest master, when I try to do `sbt assembly` to build a fat jar, I get some dependency conflict errors. I don't have any local changes to my config files and I deleted my ivy cache before the build. Does anyone know what the problem could be?

```
/home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/release.properties
	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:140)
	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
	at sbtassembly.Assembly$.apply(Assembly.scala:83)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:240)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:237)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (root/*:assembly) deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/conllu/2PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/conllu/2PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/conllu/NivreEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/conllu/NivreEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/conllu/PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/conllu/PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/conllu/StackAttardi.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/conllu/StackAttardi.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/conllx/2PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/conllx/2PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/conllx/NivreEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/conllx/NivreEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/conllx/PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/conllx/PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/conllx/StackAttardi.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/conllx/StackAttardi.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/malttab/2PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/malttab/2PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/malttab/NivreEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/malttab/NivreEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/malttab/PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/malttab/PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/malttab/StackAttardi.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/malttab/StackAttardi.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/conllu/2PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/conllu/2PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/conllu/NivreEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/conllu/NivreEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/conllu/PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/conllu/PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/conllu/StackAttardi.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/conllu/StackAttardi.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/conllx/2PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/conllx/2PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/conllx/NivreEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/conllx/NivreEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/conllx/PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/conllx/PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/conllx/StackAttardi.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/conllx/StackAttardi.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/malttab/2PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/malttab/2PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/malttab/NivreEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/malttab/NivreEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/malttab/PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/malttab/PlanarEager.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/libsvm/malttab/StackAttardi.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/libsvm/malttab/StackAttardi.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/options.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/options.xml
[error] deduplicate: different file contents found in the following:
[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/release.properties
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/release.properties
[error] Total time: 18 s, completed May 8, 2019 3:20:04 PM
```

**Comment by kwalcock** [comment]
On my machine, the two files

[error] /home/bmg16/.ivy2/cache/org.maltparser/maltparser/jars/maltparser-1.9.0.jar:appdata/features/liblinear/conllu/2PlanarEager.xml
[error] /home/bmg16/.ivy2/cache/org.clulab/processors-modelsmain_2.11/jars/processors-modelsmain_2.11-7.5.1.jar:appdata/features/liblinear/conllu/2PlanarEager.xml

differ in line endings.  The clulab version has CRLF and the malt version just has LF.  I'm trying to track down how that might have come about.  It may be that some git settings are messed up, possibly mine.

**Comment by kwalcock** [comment]
Yes, it looks like git "helpfully" converted everything in processors to CRLF, which normally doesn't matter unless I do the release and they get into something other than github.  I'm working on it.  There will probably have to be a 7.5.2 release of processors to fix it.

**Comment by kwalcock** [comment]
I reproduced the error, then re-cloned processors with the correct settings, did a publishLocal, then updated reach to use the updated version, and the problem goes away.  So, @MihaiSurdeanu, I need to do a PR to processors to update the version to 7.5.2, then republish to maven (which you want to know about), then do a PR to reach to use the updated version.  Sorry about the mistake, everyone.

**Comment by kwalcock** [comment]
That's not quite right.  The publishing process will automatically bump the version to 7.5.2.  I'll add a comment to CHANGES.md, though.

**Comment by MihaiSurdeanu** [comment]
Please do!

**Comment by kwalcock** [comment]
Is it OK to include Becky's "Enabling finding triggers through named mentions" as well?

**Comment by MihaiSurdeanu** [comment]
@BeckySharp ?

**Comment by BeckySharp** [comment]
It was merged i think, there's a unit test, i mean, as far as I'm
concerned, yes.... asking bc it's a PR from me?

**Comment by kwalcock** [comment]
Maybe it's bigger than a 0.0.1 change, perhaps it can only be used with an updated version of reach, ...  I was insufficiently paranoid the last time, so just checking.  Thanks!

**Comment by BeckySharp** [comment]
sure? :) hope it was helpful, I doubt the change will affect reach (bc it adds prev unavailable ways to write rule, rather than changing existing functionality), but hopefully if I'm wrong unit tests in reach (which i haven't run) will catch it?

**Comment by kwalcock** [comment]
It *should* be fixed (famous last words).  I'll add a unit test to help make sure it doesn't happen again.  reach master should use processors 7.5.2.

**Comment by bgyori** [comment]
Just tested the build and it works. Thanks!
